# Generated by Django 6.0.6 on 2026-07-07 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
