"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kqs8js8$93r2g+nyes5#oht6oqz(gan(0szj1$bmj61_&mc^wd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #local
    'accounts',
    'interactions',
    'news',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', #qaysi tilda ekanligini aniqlaydi
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/



TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True
LANGUAGE_CODE = 'uz'

LANGUAGES=[
    ('uz',"O'zbek"),
    ('ru',"Rus"),
    ('en',"Ingliz"),
]

LOCALE_PATHS=[BASE_DIR / 'locale']
MODELTRANSLATION_DEFAULT_LANGUAGE='uz'


USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS=[
    BASE_DIR / "static/"
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL="media/"
MEDIA_ROOT=BASE_DIR / "media"

AUTH_USER_MODEL = "accounts.User"

JAZZMIN_SETTINGS = {
    # Brauzer tabidagi nom
    "site_title": "Yangiliklar Admin Paneli",

    # Login sahifasidagi sarlavha (Maksimal 19 ta belgi)
    "site_header": "Yangiliklar",

    # Admin panel ichida chap yuqorida turadigan brend nomi
    "site_brand": "KunYangiliklari",

    # Static fayllardagi logotip yo'li (agar bo'lsa, masalan: "images/logo.png")
    "site_logo": None,

    # Login sahifasi uchun logotip
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,

    # Login oynasidagi qutlov matni
    "welcome_sign": "Yangiliklar sayti boshqaruv paneliga xush kelibsiz!",

    # Footer (eng pastki) qismidagi mualliflik huquqi
    "copyright": "KunYangiliklari OAV MChJ",

    # [TO'G'RILANDI]: Qidiruv tizimiga o'zingizning Custom User modelingizni ulaymiz
    "search_model": ["accounts.User"],

    # Agar foydalanuvchi modelida rasm (avatar) maydoni bo'lsa, shu yerga yoziladi, masalan: "avatar"
    "user_avatar": None,

    ############
    # Top Menu #
    ############
    "topmenu_links": [
        {"name": "Bosh sahifa", "url": "admin:index", "permissions": ["accounts.view_user"]},  # [TO'G'RILANDI]
        {"name": "Saytga o'tish", "url": "home", "new_window": True},
    ],

    #############
    # User Menu #
    #############
    "usermenu_links": [
        {"name": "Yordam (Support)", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "accounts.user"}  # [TO'G'RILANDI]: Profil sozlamasiga o'z profilingiz ulandi
    ],

    #############
    # Side Menu #
    #############
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # [TO'G'RILANDI]: Menyudagi ilovalarning ketma-ketlik tartibi.
    # Bu yerga o'zingiz yaratgan ilova nomini (masalan, "news" yoki "articles") qo'shib qo'ysangiz bo'ladi
    "order_with_respect_to": ["accounts", "auth"],

    # Yon menyudagi ilovalar va modellar uchun ikonkalar (FontAwesome 5)
    "icons": {
        "accounts.User": "fas fa-user-shield",  # Adminlar va foydalanuvchilar uchun qalqonli odamcha
        "auth.Group": "fas fa-users-cog",  # Guruhlar uchun sozlash ikonkiasi

        # Kelajakda yangiliklar modelini qo'shsangiz, mana bunday ikonka bersangiz bo'ladi:
        # "news.Post": "fas fa-newspaper",
        # "news.Category": "fas fa-tags",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # True qilinsa, boshqa modelni ulashda yangi oyna (popup) emas, chiroyli modal ochiladi
    "related_modal_active": True,  # [TAVSIYA]: True qilingani qulayroq

    #############
    # UI Tweaks #
    #############
    "custom_css": False,
    "custom_js": False,
}